permalink: pretty

title: Miro Garcia - Computer Science Portfolio
description: "Welcome to my professional portfolio showcasing my projects and resume."
logo: assets/IMG_1532,updated.jpg

theme: jekyll-theme-minimal

header_pages:
  - index.md
  - Projects.md
  - Resume.md

baseurl: "/personal-website"
